# Generated by Django 4.2.7 on 2024-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJBFiltration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impurest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('changelogid', models.BigIntegerField(blank=True, db_column='ChangeLogID', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('reportdate', models.TextField(blank=True, db_column='ReportDate', null=True)),
                ('subscriberid', models.BigIntegerField(blank=True, db_column='SubscriberID', null=True)),
                ('metergroupid', models.BigIntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('opening_datetime', models.TextField(blank=True, db_column='Opening_DateTime', null=True)),
                ('closing_datetime', models.TextField(blank=True, db_column='Closing_DateTime', null=True)),
                ('duration', models.FloatField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'impurest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maxruntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('changelogid', models.BigIntegerField(blank=True, db_column='ChangeLogID', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('reportdate', models.TextField(blank=True, db_column='ReportDate', null=True)),
                ('subscriberid', models.BigIntegerField(blank=True, db_column='SubscriberID', null=True)),
                ('metergroupid', models.BigIntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('opening_datetime', models.TextField(blank=True, db_column='Opening_DateTime', null=True)),
                ('closing_datetime', models.TextField(blank=True, db_column='Closing_DateTime', null=True)),
                ('duration', models.FloatField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'maxruntime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minruntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('changelogid', models.BigIntegerField(blank=True, db_column='ChangeLogID', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('reportdate', models.TextField(blank=True, db_column='ReportDate', null=True)),
                ('subscriberid', models.BigIntegerField(blank=True, db_column='SubscriberID', null=True)),
                ('metergroupid', models.BigIntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('opening_datetime', models.TextField(blank=True, db_column='Opening_DateTime', null=True)),
                ('closing_datetime', models.TextField(blank=True, db_column='Closing_DateTime', null=True)),
                ('duration', models.FloatField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'minruntime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('changelogid', models.BigIntegerField(blank=True, db_column='ChangeLogID', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('reportdate', models.TextField(blank=True, db_column='ReportDate', null=True)),
                ('subscriberid', models.BigIntegerField(blank=True, db_column='SubscriberID', null=True)),
                ('metergroupid', models.BigIntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('opening_datetime', models.TextField(blank=True, db_column='Opening_DateTime', null=True)),
                ('closing_datetime', models.TextField(blank=True, db_column='Closing_DateTime', null=True)),
                ('duration', models.FloatField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'purest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metergroupid', models.IntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('runtime', models.IntegerField(blank=True, db_column='Runtime', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'runtime_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuschange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metergroupid', models.IntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('changes', models.IntegerField(blank=True, db_column='Changes', null=True)),
            ],
            options={
                'db_table': 'statuschange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metergroupid', models.IntegerField(blank=True, db_column='MeterGroupID', null=True)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'time_cat',
                'managed': False,
            },
        ),
    ]
